rover_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10



#buranin asagisindan emin degilim, deneme asamasinda

rover_arm_right_finger:
    type: position_controllers/JointPositionController
    joint: gripper_right_joint
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_left_finger:
    type: position_controllers/JointPositionController
    joint: gripper_left_joint
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_joint_1:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
    
rover_arm_joint_2:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_joint_3:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_joint_4:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_joint_5:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}

rover_arm_joint_6:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}