global_frame: map
rolling_window: false
track_unknown_space: true
map_topic: /move_base/local_costmap/costmap

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
