footprint_topic: "footprint"
#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]] #kullanılan
#footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
robot_radius: 0.8485
#footprint_padding: 0.01 #0.01 

robot_base_frame: base_link
update_frequency: 4.0 #4.0
publish_frequency: 3.0 #4.0 #3.0
transform_tolerance: 0.5

resolution: 0.05 #0.05

obstacle_range: 6.5 #5.5
raytrace_range: 10.0 #6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    map_topic: /map
    subscribe_to_updates: true
#obstacles_pc2:
#    observation_sources: pointcloud2
#    pointcloud2: {data_type: PointCloud2,clearing: true, marking: true, topic: velodyne_points, inf_is_valid: true}
#    map_topic: /map
#    subscribe_to_updates: true

inflation:
    inflation_radius: 3.0 #1.13 #1.0 #0.1
    cost_scaling_factor: 6.0
