controller_frequency: 5.0
global_plan_topic: global_plan
global_plan_type: Path3D
global_plan_epsilon: -1.0
twist_topic: cmd_vel
twist_type: Twist3D

DluxGlobalPlanner:
  neutral_cost: 50
  scale: 3.0
  unknown_interpretation: free
  path_caching: false
  improvement_threshold: -1.0
  publish_potential: true
  print_statistics: true
  potential_calculator: dlux_plugins::AStar
  traceback: dlux_plugins::GradientPath

  # AStar
  manhattan_heuristic: false
  use_kernel: true
  minimum_requeue_change: 1.0

  # GradientPath
  step_size: 0.5
  lethal_cost: 250.0
  iteration_factor: 4.0
  grid_step_near_high: false

DWBLocalPlanner:
  update_costmap_before_planning: true
  prune_plan: false
  prune_distance: 1.0
  short_circuit_trajectory_evaluation: true
  debug_trajectory_details: false
#  publish_cost_grid_pc: true

  trajectory_generator_name: dwb_plugins::StandardTrajectoryGenerator
  # velocities
  min_vel_x: 0.0 #eski
  max_vel_x: 1.0 #eski

  max_vel_x: 0.5
  min_vel_x: 0.0

  min_vel_y: 0.0
  max_vel_y: 0.4

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2
#added after dwa
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2
  # acceleration 
  acc_lim_x: 1.0
  acc_lim_y: 0
  acc_lim_th: 3.2
  # deceleration
  decel_lim_x: -3.2
  decel_lim_y: 0.0
  decel_lim_theta: -3.2
  # absolute speeds (in either direction)
  min_speed_xy: 0.1
  max_speed_xy: 0.3
  min_speed_theta: 0.3

  goal_checker_name: dwb_plugins::SimpleGoalChecker
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  critics:
  - PreferForward
  - RotateToGoal
  - Oscillation

  - PathDist
  - PathAlign
  - GoalDist
  - GoalAlign

  # PreferForward critic
  PreferForward:
    backward_cost: 1.0
    forward_cost: 0.0
    scale: 1.0

  # RotateToGoal critic
  RotateToGoal:
    xy_goal_tolerance: 0.5
    trans_stopped_velocity: 0.1
    slowing_factor: 1.0
    lookahead_time: -1.0
    scale: 1.0

  # Oscillation critic
  Oscillation:
    x_only_threshold: 0.05
    oscillation_reset_dist: 0.05
    oscillation_reset_angle: 0.05
    oscillation_reset_time: -1.0
    scale: 1.0
  PathDist:  
    scale: 32.0  
  GoalDist:  
    scale: 25.0  
  PathAlign:  
    scale: 25.0  
    forward_point_distance: 0.325  
  GoalAlign:  
    scale: 32.0  
